// Generated by bpmn-to-code
package io.miragon.blueprint.adapter.process;

import java.util.List;

/**
 * Job worker task types used in {@code @JobWorker(type = ServiceTasks.X)} annotations.
 * Kept as {@code public static final String} because annotation arguments must be compile-time constants.
 */
public final class ServiceTasks {
  public static final String ACTIVATE_LEASING_DELEGATE = "#{activateLeasingDelegate}";

  public static final String BOOK_COSTS_DELEGATE = "#{bookCostsDelegate}";

  public static final String CANCEL_CONTRACT_DELEGATE = "#{cancelContractDelegate}";

  public static final String CANCEL_POLICY_DELEGATE = "#{cancelPolicyDelegate}";

  public static final String ISSUE_INSURANCE_POLICY_DELEGATE = "#{issueInsurancePolicyDelegate}";

  public static final String ORDER_BIKE_DELEGATE = "#{orderBikeDelegate}";

  public static final String REQUEST_CANCELLATION_DELEGATE = "#{requestCancellationDelegate}";

  public static final String SEND_CANCELLATION_CONFIRMATION_DELEGATE = "#{sendCancellationConfirmationDelegate}";

  public static final String SEND_CONTRACT_DELEGATE = "#{sendContractDelegate}";

  public static final String SEND_REJECTION_DELEGATE = "#{sendRejectionDelegate}";

  public static final String SEND_REMINDER_MAIL_DELEGATE = "#{sendReminderMailDelegate}";

  public static final String VALIDATE_APPLICATION_DELEGATE = "#{validateApplicationDelegate}";

  private ServiceTasks() {
  }

  public static List<String> all() {
    return List.of(
        ACTIVATE_LEASING_DELEGATE,
        BOOK_COSTS_DELEGATE,
        CANCEL_CONTRACT_DELEGATE,
        CANCEL_POLICY_DELEGATE,
        ISSUE_INSURANCE_POLICY_DELEGATE,
        ORDER_BIKE_DELEGATE,
        REQUEST_CANCELLATION_DELEGATE,
        SEND_CANCELLATION_CONFIRMATION_DELEGATE,
        SEND_CONTRACT_DELEGATE,
        SEND_REJECTION_DELEGATE,
        SEND_REMINDER_MAIL_DELEGATE,
        VALIDATE_APPLICATION_DELEGATE);
  }
}
