// Generated by bpmn-to-code
@file:Suppress("unused")

package io.miragon.blueprint.adapter.process

import kotlin.String
import kotlin.Suppress
import kotlin.collections.List

/**
 * Job worker task types used in `@JobWorker(type = ServiceTasks.X)` annotations.
 * Kept as `const val String` because annotation arguments must be compile-time constants.
 */
object ServiceTasks {
  const val ACTIVATE_LEASING_DELEGATE: String = "#{activateLeasingDelegate}"

  const val BOOK_COSTS_DELEGATE: String = "#{bookCostsDelegate}"

  const val CANCEL_CONTRACT_DELEGATE: String = "#{cancelContractDelegate}"

  const val CANCEL_POLICY_DELEGATE: String = "#{cancelPolicyDelegate}"

  const val ISSUE_INSURANCE_POLICY_DELEGATE: String = "#{issueInsurancePolicyDelegate}"

  const val ORDER_BIKE_DELEGATE: String = "#{orderBikeDelegate}"

  const val REQUEST_CANCELLATION_DELEGATE: String = "#{requestCancellationDelegate}"

  const val SEND_CANCELLATION_CONFIRMATION_DELEGATE: String =
      "#{sendCancellationConfirmationDelegate}"

  const val SEND_CONTRACT_DELEGATE: String = "#{sendContractDelegate}"

  const val SEND_REJECTION_DELEGATE: String = "#{sendRejectionDelegate}"

  const val SEND_REMINDER_MAIL_DELEGATE: String = "#{sendReminderMailDelegate}"

  const val VALIDATE_APPLICATION_DELEGATE: String = "#{validateApplicationDelegate}"

  val all: List<String> = listOf(
    ACTIVATE_LEASING_DELEGATE,
    BOOK_COSTS_DELEGATE,
    CANCEL_CONTRACT_DELEGATE,
    CANCEL_POLICY_DELEGATE,
    ISSUE_INSURANCE_POLICY_DELEGATE,
    ORDER_BIKE_DELEGATE,
    REQUEST_CANCELLATION_DELEGATE,
    SEND_CANCELLATION_CONFIRMATION_DELEGATE,
    SEND_CONTRACT_DELEGATE,
    SEND_REJECTION_DELEGATE,
    SEND_REMINDER_MAIL_DELEGATE,
    VALIDATE_APPLICATION_DELEGATE,
  )
}
